#!/bin/bash
# Submit individual jobs
# Usage: ./submit_individual.sh job_<exp_name>.sh

if [ $# -eq 0 ]; then
    echo 'Usage: ./submit_individual.sh job_<exp_name>.sh'
    echo 'Available jobs:'
    echo '  job_flyingthings_lr1e-4_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_flyingthings_lr1e-4_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_flyingthings_lr1e-4_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_flyingthings_lr1e-4_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_flyingthings_lr3e-4_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_flyingthings_lr3e-4_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_flyingthings_lr3e-4_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_flyingthings_lr3e-4_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_flyingthings_lr1e-3_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_flyingthings_lr1e-3_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_flyingthings_lr1e-3_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_flyingthings_lr1e-3_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_flyingthings_freezeTrue_pretrainedTrue.sh'
    echo '  job_flyingthings_freezeTrue_pretrainedFalse.sh'
    echo '  job_flyingthings_freezeFalse_pretrainedTrue.sh'
    echo '  job_flyingthings_freezeFalse_pretrainedFalse.sh'
    echo '  job_flyingthings_logstepslogarithmic_pretrainedTrue.sh'
    echo '  job_flyingthings_logstepslogarithmic_pretrainedFalse.sh'
    echo '  job_spair_lr1e-4_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_spair_lr1e-4_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_spair_lr1e-4_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_spair_lr1e-4_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_spair_lr3e-4_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_spair_lr3e-4_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_spair_lr3e-4_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_spair_lr3e-4_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_spair_lr1e-3_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_spair_lr1e-3_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_spair_lr1e-3_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_spair_lr1e-3_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_spair_freezeTrue_pretrainedTrue.sh'
    echo '  job_spair_freezeTrue_pretrainedFalse.sh'
    echo '  job_spair_freezeFalse_pretrainedTrue.sh'
    echo '  job_spair_freezeFalse_pretrainedFalse.sh'
    echo '  job_spair_logstepslogarithmic_pretrainedTrue.sh'
    echo '  job_spair_logstepslogarithmic_pretrainedFalse.sh'
    echo '  job_pointodyssey_lr1e-4_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_pointodyssey_lr1e-4_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_pointodyssey_lr1e-4_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_pointodyssey_lr1e-4_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_pointodyssey_lr3e-4_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_pointodyssey_lr3e-4_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_pointodyssey_lr3e-4_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_pointodyssey_lr3e-4_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_pointodyssey_lr1e-3_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_pointodyssey_lr1e-3_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_pointodyssey_lr1e-3_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_pointodyssey_lr1e-3_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_pointodyssey_freezeTrue_pretrainedTrue.sh'
    echo '  job_pointodyssey_freezeTrue_pretrainedFalse.sh'
    echo '  job_pointodyssey_freezeFalse_pretrainedTrue.sh'
    echo '  job_pointodyssey_freezeFalse_pretrainedFalse.sh'
    echo '  job_pointodyssey_logstepslogarithmic_pretrainedTrue.sh'
    echo '  job_pointodyssey_logstepslogarithmic_pretrainedFalse.sh'
    echo '  job_synthetic_lr1e-4_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_synthetic_lr1e-4_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_synthetic_lr1e-4_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_synthetic_lr1e-4_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_synthetic_lr3e-4_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_synthetic_lr3e-4_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_synthetic_lr3e-4_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_synthetic_lr3e-4_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_synthetic_lr1e-3_lrbackbone1e-6_pretrainedTrue.sh'
    echo '  job_synthetic_lr1e-3_lrbackbone1e-6_pretrainedFalse.sh'
    echo '  job_synthetic_lr1e-3_lrbackbone3e-6_pretrainedTrue.sh'
    echo '  job_synthetic_lr1e-3_lrbackbone3e-6_pretrainedFalse.sh'
    echo '  job_synthetic_freezeTrue_pretrainedTrue.sh'
    echo '  job_synthetic_freezeTrue_pretrainedFalse.sh'
    echo '  job_synthetic_freezeFalse_pretrainedTrue.sh'
    echo '  job_synthetic_freezeFalse_pretrainedFalse.sh'
    echo '  job_synthetic_logstepslogarithmic_pretrainedTrue.sh'
    echo '  job_synthetic_logstepslogarithmic_pretrainedFalse.sh'
    exit 1
fi

sbatch "$1"
