model:
  type: glunet
  glunet:
    model_name: resnet50
    local_window_size: 9
    decoder_dense_connect: false
  pretrained_backbone: true
  freeze: false
training:
  epochs: 100
  batch_size: 8
  n_threads: 4
  seed: 2021
  lr: 0.001
  lr_backbone: 1.0e-05
  weight_decay: 0.0005
  momentum: 0.9
  scheduler: cosine
  step: '[70, 80, 90]'
  step_gamma: 0.5
  gradient_clip_val: 1.0
  steps_per_epoch: 100
  check_val_every_n_epoch: 5
  augmentation: false
  min_flow_length: null
  max_flow_length: null
  mmd_every_n_epochs: 0
  eval_initial: false
  enable_debug: false
  debug_visualization_benchmarks: null
  debug_visualization_persist: false
dataset:
  dataset_name: kubric_intervention
  split: train
  size:
  - 512
  - 512
  downsample_flow: null
  max_kps: null
  dense_kps_use_all: true
  verbose: false
  debug: false
  normalize_images: true
  datapath: /mnt/nvme_1tb_a/kubric_interventions/ladder/kitti_m050_matte
  reverse_flow: false
evaluation:
  eval_benchmarks:
  - kitti2015
  - kitti2012
  - middlebury
  - flyingthings
  eval_alphas:
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  thres: img
  split_to_use_for_validation: test
  val_batch_size: 8
  val_num_workers: 8
  prefetch_factor: 2
  use_motion_aware: false
  min_motion_pixels: 5.0
  zero_threshold: 0.5
  datapath: ./models/Datasets_CATs
  tss_root: /home/spencer/Data/correspondence/TSS_CVPR2016
  kitti_root: /home/spencer/Data/correspondence/kitti
  kitti_val_use_full_training: true
  pointodyssey_root: /home/spencer/Data/PointOdyssey
  flyingthings_root: /home/spencer/Data/FlyingThings3D_tiny
  middlebury_root: /home/spencer/Data/middlebury/all
  val_datasets:
    kitti2012:
      split: val
      normalize_images: true
    kitti2015:
      split: val
      normalize_images: true
    flyingthings:
      split: test
      normalize_images: true
      val_dataset_fraction: 0.2
    middlebury:
      normalize_images: true
      reverse_flow: false
paths:
  snapshots: /mnt/nvme_1tb_a/snapshots/transfer_grid_glunet_ladder
  pretrained: null
  start_epoch: 0
  save_epoch_checkpoints: false
