raytune:
  val_data_name: tss
  log_dir: ${oc.env:HOME_DIR}/raytune_logs_fixed/
  num_cpus: 64
  num_gpus: 2
  num_workers: 1
  cpus_per_worker: 15
  gpus_per_worker: 0.5
  max_t: 40
  grace_period: 5
  num_samples: 100
  reuse_actors: true
  num_to_keep: 100
  concurrent_trials: 4
  raytune_datamodule: src.data.synth_real_mixed.SynthRealMixedDatamodule 