val_data:
  class_path: src.data.real.datamodule.TSSDatamodule
  init_args:
    root: ${oc.env:DATADIR}/correspondence/TSS_CVPR2016/
    size: 256
    normalize: true
    batch_size: 32
    num_workers: 7
    shuffle: false
  