dataset:
  dataset_name: synthetic
  debug: false
  dense_kps_use_all: true
  downsample_flow: null
  geometry_config_overrides:
    angle_sampler:
      x_components:
        loc: 0
        scale: 0.01
      y_components:
        loc: 0
        scale: 0.01
    scale_sampler:
      abs_components:
        scale: 0.5
      rel_components:
        loc: -0.35
        scale: 0.5
  geometry_config_path: src/configs/online_synth_configs/OnlineGeometryConfig.yaml
  max_kps: null
  normalize_images: false
  opengl_device_index: null
  processor_config_path: src/configs/online_synth_configs/OnlineProcessorConfig.yaml
  size:
  - 512
  - 512
  split: train
  verbose: false
model:
  freeze: false
  glunet:
    decoder_dense_connect: false
    local_window_size: 9
    model_name: resnet50
  pretrained_backbone: true
  type: glunet
evaluation:
  datapath: ./models/Datasets_CATs
  eval_alphas:
  - 0.05
  - 0.03
  eval_benchmarks:
  - tss
  - tapvid_davis
  min_motion_pixels: 5.0
  prefetch_factor: 2
  split_to_use_for_validation: test
  thres: img
  tss_root: /home/spencer/Data/correspondence/TSS_CVPR2016
  use_motion_aware: false
  val_batch_size: 2
  val_num_workers: 2
  zero_threshold: 0.5
  kitti_root: /home/spencer/Data/correspondence/kitti
  kitti_val_use_full_training: true
  tapvid_davis_root: /mnt/nvme_1tb_a/tapvid/probe_cache
  val_datasets:
    tapvid_davis:
      tapvid_stride: 6
      tapvid_frame_step: 5
      tapvid_min_pts: 1
      reverse_flow: true
      normalize_images: true
    kitti2015:
      split: val
      normalize_images: true
    kitti2012:
      split: val
      normalize_images: true
training:
  accumulate_grad_batches: 1
  augmentation: false
  batch_size: 8
  check_val_every_n_epoch: 1
  epochs: 15
  eval_initial: true
  lr: 0.001
  lr_backbone: 1.0e-05
  max_flow_length: null
  min_flow_length: null
  mmd_every_n_epochs: 0
  momentum: 0.9
  n_threads: 2
  scheduler: step
  seed: 2021
  step: '[70, 80, 90]'
  step_gamma: 0.5
  steps_per_epoch: 100
  weight_decay: 0.0005
paths:
  snapshots: /mnt/nvme_1tb_a/snapshots/kubvar/synth_large_zoom_glunet_tf
  save_epoch_checkpoints: false
  start_epoch: 0
  pretrained: null
