seed_everything: 777777777
trainer:
  enable_checkpointing: false
  default_root_dir: logs/julia/run-418
  num_nodes: 1
  devices: 1
  accelerator: gpu
  strategy: auto
  enable_progress_bar: true
  check_val_every_n_epoch: 1
  max_epochs: 25
  log_every_n_steps: 50
  precision: 16-mixed
  num_sanity_val_steps: 0
  gradient_clip_val: 1.0
  callbacks:
  - class_path: src.callbacks.progress_callback.PrintProgressCallback
    init_args:
      print_interval: 10
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: ${trainer.default_root_dir}
      name: eval
      version: awa
      flush_logs_every_n_steps: 20
data:
  class_path: src.data.real.datamodule.AWADatamodule
  init_args:
    root: ${oc.env:DATADIR}/correspondence/AwAPose/AwA-Pose/
    thres: bbox
    normalize: true
    batch_size: 32
    num_workers: 5
model:
  class_path: src.model.training.DirectMultiEPE
  init_args:
    model:
      class_path: src.model.glunet.sem_glunet.SemanticGLUNet
      init_args:
        model_name: resnet50
        weights: IMAGENET1K_V2
        freeze: true
        local_window_size: 9
        decoder_dense_connect: false
    finetune: none
    lr: 0.001
    ft_lr_scale: 0.01
    warmup: 0.05
    weight_decay: 0.0005
    eval_metric: pck@0.1
    src_key: src_img
    trg_key: trg_img
    flow_key: null
ckpt_path: logs/julia/run-418/checkpoints/epoch=24.ckpt
