trainer:
  enable_checkpointing: false
  num_nodes: 1
  devices: 1
  accelerator: gpu
  strategy: auto
  enable_progress_bar: true
  callbacks:
  - class_path: src.callbacks.progress_callback.PrintProgressCallback
    init_args:
      print_interval: 10
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: ${trainer.default_root_dir}
      name: eval
      version: "???"
      flush_logs_every_n_steps: 20