seed_everything: 555555555
trainer:
  enable_checkpointing: true
  default_root_dir: logs/__tests/raytune0
  num_nodes: 1
  devices: 1
  accelerator: gpu
  strategy: auto
  enable_progress_bar: true
  check_val_every_n_epoch: 1
  max_epochs: 100
  log_every_n_steps: 50
  precision: 16-mixed
  num_sanity_val_steps: 0
  gradient_clip_val: 1.0
  use_distributed_sampler: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      dirpath: ${trainer.default_root_dir}/checkpoints
      filename: '{epoch}'
      save_weights_only: false
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
  - class_path: src.callbacks.progress_callback.PrintProgressCallback
  - class_path: src.callbacks.ckpt_squeeze_callback.CheckpointSqueezeCallback
    init_args:
      policy: all
  logger:
  - class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: ${trainer.default_root_dir}/tensorboard
      name: ''

data:
  class_path: src.data.synth.datamodule.OnlineComponentsDatamodule
  init_args:
    root: ${oc.env:WORKDIR}/rendering/shaders/quatJulia.c
    shaders:
      program0: ${oc.env:WORKDIR}/rendering/shaders/terrain_sdf.glsl
      # program1: ${oc.env:WORKDIR}/rendering/shaders/quatJulia.c
      # program2: ${oc.env:WORKDIR}/rendering/shaders/mandelbulb.glsl
      # program3: ${oc.env:WORKDIR}/rendering/shaders/quatJulia.c
      # program4: ${oc.env:WORKDIR}/rendering/shaders/mandelbulb.glsl
      # program5: ${oc.env:WORKDIR}/rendering/shaders/sphere.glsl
      merge: ${oc.env:WORKDIR}/rendering/shaders/merge.glsl
      # anti_alias: ${oc.env:WORKDIR}/rendering/shaders/anti_alias.glsl
    # root: ${oc.env:WORKDIR}/rendering/shaders/original_julia.glsl
    # root: ${oc.env:WORKDIR}/rendering/shaders/landscape.glsl
    # root: ${oc.env:WORKDIR}/rendering/shaders/menger_cube.glsl
    val_root: ${oc.env:DATADIR}/synthetic/
    num_samples: 8000
    num_samples_val: 1024
    background_sampler: null
    foreground_sampler:
      matching_prob: 1.0
      texture_scale:
        alpha:
          - 2.0
          - 3.0
    use_video_sampler: false
    use_grf_sampler: false
    use_worley_sampler: true
    worley_sampler_dict:
      matching_prob: 1.0
      terrain_matching_prob: 0.50
      texture_scale0:
        alpha:
          offset: 0.5
          scale: 7.5
      texture_scale1:
        alpha:
          offset: 20.0
          scale: 80.0
      mixing_param0:
        alpha:
          offset: 0.0
          scale: 1.0
      mixing_param1:
        alpha:
          offset: 0.0
          scale: 1.0
      terrain_texture_scale0:
        alpha:
          offset: 0.0
          scale: 0.5
      terrain_texture_scale1:
        alpha:
          offset: 10.0
          scale: 40.0
      terrain_mixing_param0:
        alpha:
          offset: 0.0
          scale: 1.0
      terrain_mixing_param1:
        alpha:
          offset: 0.0
          scale: 1.0
    mandelbulb_sampler:
      power_range:
        min: 1.5
        offset: 2.5
    julia_sampler:
      distribution: uniform
      loc: 3
      scale: 9
    angle_sampler:
      x_components:
        distribution: uniform
        loc: -0.25
        scale: 0.5
      y_components:
        distribution: uniform
        loc: -0.16667
        scale: 0.33333
    scale_sampler:
      abs_components:
        distribution: uniform
        loc: 0.5
        scale: 0.4
      rel_components:
        distribution: uniform
        loc: -0.35
        scale: 0.35
    bg_color_sampler_dict:
      matching_prob: 0.5
      hue_offset: 0.0
      hue_scale: 1.0
      saturation_offset: 0.0
      saturation_scale: 0.5
      value_offset: 0.25
      value_scale: 0.75
    img_res: 256
    random_flip: 0.25
    normalize: imagenet
    batch_size: 32
    shuffle: true
    num_workers: 7
    texture_resolution: 64
    seed: 555555574

model:
  class_path: src.model.glunet.glunet_lightning.GLUNet
  init_args:
    model_kwargs:
      model_name: resnet50
      weights: IMAGENET1K_V2
      freeze: true
      local_window_size: 9
      decoder_dense_connect: false
    checkpoint: null
    finetune: auto
    src_key: src
    trg_key: trg
    val_src_key: src_img
    val_trg_key: trg_img
    flow_key: flow
    bidirectional_eval: false
    eval_metric: pck@0.1
    lr: 0.001
    ft_lr_scale: 0.01
    warmup: 0.05
    weight_decay: 0.0005

val_data:
  class_path: src.data.real.datamodule.SemanticFlowDatamodule
  init_args:
    root: ${oc.env:DATADIR}/correspondence
    benchmark: spair
    thres: bbox
    data_kw:
      feature_size: 256
      normalize: true
    batch_size: 32
    num_workers: 7

raytune:
  val_data_name: spair
  log_dir: /home/slow1/raytune_logs/
  num_cpus: 29
  num_workers: 4
  cpus_per_worker: 7
  gpus_per_worker: 1
  max_t: 40
  grace_period: 5
  num_samples: 100
  reuse_actors: true
  num_to_keep: 100