seed: 987654321
normalize: 'imagenet'

# Worley sampler configuration
worley_sampler_dict:
  matching_prob: 0.50
  terrain_matching_prob: 0.50
  texture_scale0:
    alpha:
      offset: 0.5
      scale: 7.5
  texture_scale1:
    alpha:
      offset: 20.0
      scale: 80.0
  mixing_param0:
    alpha:
      offset: 0.0
      scale: 0.0
  mixing_param1:
    alpha:
      offset: 0.0
      scale: 0.0
  terrain_texture_scale0:
    alpha:
      offset: 0.0
      scale: 0.5
  terrain_texture_scale1:
    alpha:
      offset: 10.0
      scale: 40.0
  terrain_mixing_param0:
    alpha:
      offset: 0.0
      scale: 0.0
  terrain_mixing_param1:
    alpha:
      offset: 0.0
      scale: 0.0

# Background color sampler configuration
bg_color_sampler_dict:
  matching_prob: 0.5
  hue_offset: 0.0
  hue_scale: 1.0
  saturation_offset: 0.0
  saturation_scale: 0.5
  value_offset: 0.25
  value_scale: 0.75

# Sampler configuration
use_worley_sampler: true
use_grf_sampler: false

subsample_flow: 0.1
subsample_during_train: true
subsample_during_val: false
subsample_without_trainer: false