# Online Synthetic Correspondence Configuration
# Based on test_datamodule.py hardcoded settings

# Data paths
data:
  root: "/home/spencer/Deployments/synthetic-correspondence/rendering/shaders/quatJulia.c"
  val_root: "/tmp/synthetic/"  # Uses DATADIR env var with fallback to /tmp

# Shader configurations
shaders:
  program0: "/home/spencer/Deployments/synthetic-correspondence/rendering/shaders/terrain_sdf.glsl"
  program1: "/home/spencer/Deployments/synthetic-correspondence/rendering/shaders/quatJulia.c"
  program2: "/home/spencer/Deployments/synthetic-correspondence/rendering/shaders/mandelbulb.glsl"
  program3: "/home/spencer/Deployments/synthetic-correspondence/rendering/shaders/deformed_sphere.glsl"
  merge: "/home/spencer/Deployments/synthetic-correspondence/rendering/shaders/merge.glsl"

# Worley sampler configuration
worley_sampler:
  matching_prob: 0.50
  terrain_matching_prob: 0.50
  texture_scale0:
    alpha:
      offset: 0.5
      scale: 7.5
  texture_scale1:
    alpha:
      offset: 20.0
      scale: 80.0
  mixing_param0:
    alpha:
      offset: 0.0
      scale: 0.0
  mixing_param1:
    alpha:
      offset: 0.0
      scale: 0.0
  terrain_texture_scale0:
    alpha:
      offset: 0.0
      scale: 0.5
  terrain_texture_scale1:
    alpha:
      offset: 10.0
      scale: 40.0
  terrain_mixing_param0:
    alpha:
      offset: 0.0
      scale: 0.0
  terrain_mixing_param1:
    alpha:
      offset: 0.0
      scale: 0.0

# Mandelbulb sampler configuration
mandelbulb_sampler:
  power_range:
    min: 1.5
    offset: 2.5

# Background color sampler configuration
bg_color_sampler:
  matching_prob: 0.5
  hue_offset: 0.0
  hue_scale: 1.0
  saturation_offset: 0.0
  saturation_scale: 0.5
  value_offset: 0.25
  value_scale: 0.75

# Datamodule settings
datamodule:
  # Batch configuration
  batch_size: 32
  num_workers: 4  # Number of data loading workers
  pin_memory: true
  persistent_workers: true
  
  # Data loading behavior
  shuffle: true
  drop_last: false
  
  # Dataset size and sampling
  num_samples: 100  # Total number of samples to generate
  train_split: 0.8    # Fraction of data for training
  val_split: 0.1      # Fraction of data for validation
  test_split: 0.1     # Fraction of data for testing
  
  # Image configuration
  image_size: [256, 256]  # [height, width]
  channels: 3             # RGB channels
  
  # Sampler configuration
  use_worley_sampler: true
  use_grf_sampler: false
  
  # Random seed
  seed: null  # Will be set to random value if null
  
  # Data augmentation (optional)
  augmentation:
    enabled: false
    rotation_range: 15.0
    scale_range: [0.9, 1.1]
    brightness_range: 0.2
    contrast_range: 0.2
